#!/bin/bash
#Set if you have cache
SSTATE_CACHE=/storage/sstate-cache
SOURCE_MIRROR=/storage/downloads


ROOTDIR=$PWD

#For generate machine conf
SDT_LOCATION=vivado-hw/sdt
LOPPER=$(which lopper)

#Lopper is currently dependent on Vitis version (2026.1 EDF relies on newer lopper)
if [[ $LOPPER == *"2025.2"* ]]; then
    repo init -u https://github.com/Xilinx/yocto-manifests.git -b rel-v2025.2 -m default-edf.xml
    HW_PROJECT=ve2302_oob_2025_2
elif [[ $LOPPER == *"2026.1"* ]]; then
    repo init -u https://github.com/Xilinx/yocto-manifests.git -b rel-v2026.1 -m default-edf.xml
    HW_PROJECT=ve2302_oob_2026_1
else
    echo "Local lopper installation not supported, cannot figure out required EDF version"
    exit 1
fi


#Patch for Cisco Umbrella
patch -p1 --ignore-whitespace << 'EOF'
--- a/.repo/repo/project.py
+++ b/.repo/repo/project.py
@@ -3039,6 +3039,7 @@ class Project:
             tmpPath,
             "--netrc-optional",
             "--location",
+            "--insecure",
         ]
         if quiet:
             cmd += ["--silent", "--show-error"]
EOF

repo sync

source edf-init-build-env

cd $ROOTDIR

#Build HW
cd vivado-hw
make -f Makefile DESIGN_NAME=$HW_PROJECT
cd ..

#Check that we have SDT
if [ ! -d $SDT_LOCATION ]; then
  echo "Vivado SDT articats do not exist, possibly failed build"
  exit 1
fi


sources/meta-xilinx/gen-machine-conf/gen-machine-conf parse-sdt --hw-description $SDT_LOCATION -c build/conf -l build/conf/local.conf --machine-name versal-generic-xcve2302

cd build

bitbake-layers add-layer ../sources/meta-user


if [ "$SSTATE_CACHE" != "" ]; then
echo "SSTATE_DIR ?= \"$SSTATE_CACHE\"" >> conf/local.conf
fi
if [[ "$SOURCE_MIRROR" != "" ]]; then
echo "SOURCE_MIRROR_URL ?= \"$SOURCE_MIRROR\"" >> conf/local.conf
fi

#Enable usage of generic EDF linux image for Versal by specifying it from commandline
sed -i '/MACHINE = \"versal-generic-xcve2302\"/d' conf/local.conf

MACHINE=versal-generic-xcve2302 bitbake xilinx-bootbin
MACHINE=amd-cortexa72-common bitbake edf-linux-disk-image

wic cp tmp/deploy/images/versal-generic-xcve2302/boot.bin tmp/deploy/images/amd-cortexa72-common/edf-linux-disk-image-amd-cortexa72-common.rootfs.wic:1

echo "WIC image ready, copy it to sd-card with command:"
echo "sudo dd if=tmp/deploy/images/amd-cortexa72-common/edf-linux-disk-image-amd-cortexa72-common.rootfs.wic of=/dev/<your sd card> bs=1M status=progress oflag=sync"

exit 0
