#!/bin/bash
###########################################################################
#This is WIP, not all steps still in script
###########################################################################
DEVICE="xcve2302-sfva784-1LP-e-S"

ROOTDIR=$PWD
XPFM=$ROOTDIR/vitis/build/workspace/versal-generic-xcve2302_platform/export/versal-generic-xcve2302_platform/versal-generic-xcve2302_platform.xpfm
XODIR=$ROOTDIR/vitis/build/xo_hw/

main ()
{

    parse_cmd "$@"
    
    set $ROOTDIR/build
    source edf-init-build-env

    cd $ROOTDIR
    mkdir -p vitis/build/xo_hw/

    #Build xpfm platform
    cd vitis/xpfm_creation/
    vitis -s build_platform.py --rootdir=$ROOTDIR

    #Build IP

    #vadd_s
    cd $ROOTDIR/vitis/ip/vadd_s
    compile_hls "vadd_s"

    #mm2s_vadd_s
    cd $ROOTDIR/vitis/ip/mm2s_vadd_s
    compile_hls "mm2s_vadd_s"
    
    #s2mm_vadd_s
    cd $ROOTDIR/vitis/ip/s2mm_vadd_s
    compile_hls "s2mm_vadd_s"

    #counter
    mkdir -p $ROOTDIR/vitis/build/xo_hw/counter
    cd $ROOTDIR/vitis/build/xo_hw/counter
    vivado -mode batch -source ${ROOTDIR}/vitis/ip/counter/pack_kernel.tcl -tclargs counter ${DEVICE} ${XODIR}/counter.xo ${ROOTDIR}/vitis/ip/counter

    #subtractor
    mkdir -p $ROOTDIR/vitis/build/xo_hw/subtractor
    cd $ROOTDIR/vitis/build/xo_hw/subtractor
    vivado -mode batch -source ${ROOTDIR}/vitis/ip/subtractor/pack_kernel.tcl -tclargs subtractor ${DEVICE} ${XODIR}/subtractor.xo ${ROOTDIR}/vitis/ip/subtractor

    #aie
    mkdir -p $ROOTDIR/vitis/build/xo_hw/aie
    cd $ROOTDIR/vitis/ip/aie

    aiecompiler \
	-include=./src -include=./src/graphs -include=./src/kernels \
	-target=hw -v --platform=${XPFM} --workdir=${XODIR}/aie/Work \
        --constraints=./src/datamove_app.aiecst \
	./src/datamove_app.cpp \
        --output-archive=${XODIR}/libadf.a \
	--kernel-linting -xlopt=1 -Xmapper=BufferOptLevel7 --pl-freq=500.0 \
        --pl-register-threshold=125 --log-level=5 --test-iterations=-1 \
        --pl-axi-lite=false \
	|& tee ${XODIR}/aie/aiecompiler.log
    
}

compile_hls ()
{
    v++ --compile --debug --save-temps \
        --platform ${XPFM} \
        --kernel $1 \
        --output ${XODIR}/$1.xo \
        --log_dir ${XODIR}/$1/log \
        --temp_dir ${XODIR}/$1/work \
        --report_dir ${XODIR}/$1/report \
        ./src/$1.cpp
}


parse_cmd ()
{
    __usage="
Usage: $(basename $0) [OPTIONS]

Options:
  -clean                 Clean build artifacts
  -h, --help             Help text

Example:
$(basename $0) -platform -sstate /storage/sstate

"
    while [[ $# -gt 0 ]]; do
        case $1 in
            -clean)
                echo "Cleaning Vitis build results"
                rm -rf vitis/build/workspace/*
                rm -rf vitis/build/xo_hw/*
                find vitis -name xcd.log | xargs rm -f
                exit 0
                ;;
            -h|--help)
                echo "$__usage"
                shift
                exit 0
                ;;
            -*|--*)
                echo "Unknown option $1"
                exit 1
                ;;
            *)
                shift
                ;;
        esac
    done

}


#Trick as bash does not have forward declarations
main "$@"
