#!/bin/bash
###########################################################################
#This is WIP, not all steps still in script
###########################################################################
DEVICE="xcve2302-sfva784-1LP-e-S"

ROOTDIR=$PWD
XPFM=$ROOTDIR/vitis/build/workspace/versal-generic-xcve2302_platform/export/versal-generic-xcve2302_platform/versal-generic-xcve2302_platform.xpfm
XODIR=$ROOTDIR/vitis/build/xo_hw/

export ROOTDIR

main ()
{

    parse_cmd "$@"
    
    set $ROOTDIR/build
    source edf-init-build-env

    cd $ROOTDIR
    mkdir -p vitis/build/xo_hw/
    mkdir -p vitis/build/linux/

    #Populate SDK
    if [ ! -d $ROOTDIR/vitis/build/sdk ]; then
        echo "Installing SDK, this will take a while"
        $ROOTDIR/build/tmp/deploy/sdk/amd-edf-glibc-x86_64-meta-edf-app-sdk-cortexa72-cortexa53-amd-cortexa72-common-toolchain-*.sh -y -d $ROOTDIR/vitis/build/sdk
    else
        echo "SDK already installed"
    fi
    
    #Build xpfm platform
    if [ ! -d vitis/build/workspace/versal-generic-xcve2302_platform/ ]; then 
        cd vitis/xpfm_creation/
        vitis -s build_platform.py --rootdir=$ROOTDIR
    fi
    
    #Build IP

    #vadd_s
    cd $ROOTDIR/vitis/ip/vadd_s
    compile_hls "vadd_s"

    #mm2s_vadd_s
    cd $ROOTDIR/vitis/ip/mm2s_vadd_s
    compile_hls "mm2s_vadd_s"
    
    #s2mm_vadd_s
    cd $ROOTDIR/vitis/ip/s2mm_vadd_s
    compile_hls "s2mm_vadd_s"

    #counter
    if [ ! -f $XODIR/counter.xo ]; then 
        mkdir -p $ROOTDIR/vitis/build/xo_hw/counter
        cd $ROOTDIR/vitis/build/xo_hw/counter
        vivado -mode batch -source ${ROOTDIR}/vitis/ip/counter/pack_kernel.tcl -tclargs counter ${DEVICE} ${XODIR}/counter.xo ${ROOTDIR}/vitis/ip/counter
    else
        echo "Skipping already compiled counter"
    fi
    
    
    #subtractor
    if [ ! -f $XODIR/subtractor.xo ]; then 
        mkdir -p $ROOTDIR/vitis/build/xo_hw/subtractor
        cd $ROOTDIR/vitis/build/xo_hw/subtractor
        vivado -mode batch -source ${ROOTDIR}/vitis/ip/subtractor/pack_kernel.tcl -tclargs subtractor ${DEVICE} ${XODIR}/subtractor.xo ${ROOTDIR}/vitis/ip/subtractor
    else
        echo "Skipping already compiled: subtractor"
    fi

    #aie
    mkdir -p $ROOTDIR/vitis/build/xo_hw/aie
    cd $ROOTDIR/vitis/ip/aie

    if [ ! -f $XODIR/libadf.a ]; then 
        aiecompiler \
	    -include=./src -include=./src/graphs -include=./src/kernels \
	    -target=hw -v --platform=${XPFM} --workdir=${XODIR}/aie/Work \
            --constraints=./src/datamove_app.aiecst \
	    ./src/datamove_app.cpp \
            --output-archive=${XODIR}/libadf.a \
	    --kernel-linting -xlopt=1 -Xmapper=BufferOptLevel7 --pl-freq=500.0 \
            --pl-register-threshold=125 --log-level=5 --test-iterations=-1 \
            --pl-axi-lite=false \
	    |& tee ${XODIR}/aie/aiecompiler.log
    else
        echo "Skipping already compiled: aie"
    fi

    #Link the design
    cd $ROOTDIR

    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    # This linking will fail unless the VE2302 board files are copied to
    # .../Xilinx/2026.1/data/xhub/boards/XilinxBoardStore/boards/Xilinx
    # directory. vpl does not seem to honor Vivado_init.tcl, the vivado
    # parameter below does not work either
    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    
    if [ ! -f $ROOTDIR/vitis/build/platform/versal-generic-xcve2302_linked.xsa ]; then 
    v++ --link --debug --save-temps \
        --vivado.param "board.repoPaths=vivado-hw/bdf_local" \
	--target hw \
	--platform ${XPFM} \
	--config vitis/system.cfg \
        vitis/build/xo_hw/counter.xo \
        vitis/build/xo_hw/mm2s_vadd_s.xo \
        vitis/build/xo_hw/s2mm_vadd_s.xo \
        vitis/build/xo_hw/subtractor.xo \
        vitis/build/xo_hw/vadd_s.xo \
        vitis/build/xo_hw/libadf.a \
	--output vitis/build/platform/versal-generic-xcve2302_linked.xsa \
        --log_dir vitis/build/platform/log \
        --temp_dir vitis/build/platform/work \
        --report_dir vitis/build/platform/report \
	|& tee vitis/build/vpp_link.log
    else
        echo "Skipping linking"
    fi

    #Build Linux apps
    make all -C $ROOTDIR/vitis/linux/aie_dly_test
    make all -C $ROOTDIR/vitis/linux/vadd_s

    #Package eveything
    mkdir -p vitis/build/sdcard/
   
   v++ --package --debug --save-temps \
		--target hw \
		--platform ${XPFM} \
		--package.out_dir vitis/build/sdcard/ \
		--package.boot_mode=sd \
		--package.image_format=ext4 \
		--package.kernel_image=${ROOTDIR}/build/tmp/deploy/images/versal-generic-xcve2302/Image \
		--package.rootfs=${ROOTDIR}/build/tmp/deploy/images/versal-generic-xcve2302/edf-platform-disk-image-versal-generic-xcve2302.rootfs.ext4  \
		vitis/build/xo_hw/libadf.a \
		vitis/build/platform/versal-generic-xcve2302_linked.xsa \
		--package.sd_file=vitis/build/linux/aie_dly_test \
		--package.sd_file=vitis/build/linux/vadd_s \
		|& tee build/vpp_pack.log 
}

compile_hls ()
{
    if [ ! -f $XODIR/$1.xo ]; then 
        v++ --compile --debug --save-temps \
            --platform ${XPFM} \
            --kernel $1 \
            --output ${XODIR}/$1.xo \
            --log_dir ${XODIR}/$1/log \
            --temp_dir ${XODIR}/$1/work \
            --report_dir ${XODIR}/$1/report \
            ./src/$1.cpp
    else
        echo "Skipping already compiled: $1"
    fi
}


parse_cmd ()
{
    __usage="
Usage: $(basename $0) [OPTIONS]

Options:
  -clean                 Clean build artifacts
  -h, --help             Help text

Example:
$(basename $0) -platform -sstate /storage/sstate

"
    while [[ $# -gt 0 ]]; do
        case $1 in
            -clean)
                echo "Cleaning Vitis build results"
                rm -rf vitis/build/workspace/*
                rm -rf vitis/build/xo_hw/*
                rm -rf vitis/build/platform/*
                rm -rf vitis/build/linux/*
                rm -rf vitis/build/sdk
                find vitis -name xcd.log | xargs rm -f
                exit 0
                ;;
            -h|--help)
                echo "$__usage"
                shift
                exit 0
                ;;
            -*|--*)
                echo "Unknown option $1"
                exit 1
                ;;
            *)
                shift
                ;;
        esac
    done

}


#Trick as bash does not have forward declarations
main "$@"
