#!/bin/bash
ROOTDIR=$PWD

#For generate machine conf
SDT_LOCATION=/storage/avnet/petalinux-ve2302-oob/vivado-hw/sdt

#Set if you have cache
SSTATE_CACHE=/storage/sstate-cache
SOURCE_MIRROR=/storage/downloads


repo init -u https://github.com/Xilinx/yocto-manifests.git -b rel-v2025.2 -m default-edf.xml

#Patch for Cisco Umbrella
patch -p1 --ignore-whitespace << 'EOF'
--- a/.repo/repo/project.py
+++ b/.repo/repo/project.py
@@ -3039,6 +3039,7 @@ class Project:
             tmpPath,
             "--netrc-optional",
             "--location",
+            "--insecure",
         ]
         if quiet:
             cmd += ["--silent", "--show-error"]
EOF

repo sync

source edf-init-build-env

cd $ROOTDIR

sources/meta-xilinx/gen-machine-conf/gen-machine-conf parse-sdt --hw-description $SDT_LOCATION -c build/conf -l build/conf/local.conf --machine-name versal-generic-xcve2302

cd build

bitbake-layers add-layer ../sources/meta-user


if [ "$SSTATE_CACHE" != "" ]; then
echo "SSTATE_DIR ?= \"$SSTATE_CACHE\"" >> conf/local.conf
fi
if [[ "$SOURCE_MIRROR" != "" ]]; then
echo "SOURCE_MIRROR_URL ?= \"$SOURCE_MIRROR\"" >> conf/local.conf
fi

#Enable usage of generic EDF linux image for Versal by specifying it from commandline
sed -i '/MACHINE = \"versal-generic-xcve2302\"/d' conf/local.conf

MACHINE=versal-generic-xcve2302 bitbake xilinx-bootbin
MACHINE=amd-cortexa72-common bitbake edf-linux-disk-image

wic cp tmp/deploy/images/versal-generic-xcve2302/boot.bin tmp/deploy/images/amd-cortexa72-common/edf-linux-disk-image-amd-cortexa72-common.rootfs.wic:1

echo "WIC image ready, copy it to sd-card with command:"
echo "sudo dd if=tmp/deploy/images/amd-cortexa72-common/edf-linux-disk-image-amd-cortexa72-common.rootfs.wic of=/dev/<your sd card> bs=1M status=progress oflag=sync"

exit 0
